### PR TITLE
closes #38

### LINKED ISSUE #38: Do not print out gigantic tableaux
Modify `show` so that too large tableaux do not pollute the CLI

### PR DESCRIPTION
**Pull request by adrianariton**
## Problem
Tableuxs, PauliOps and CliffordOps with large dimensions fill the terminal when printed.

## Solution
Parametrize the ```show``` functions with 2 params: `limit` (horizontal limit) and `limit_vertical` , each with default values
of 50 and 20 respectively. And limit the output accordingly.

## Extra
If the limits are set to `-1` the output is full.

## Approach
Create an `xz2str_limited` function that transforms an x,z tuple array to strings with length limited by `limit` (`"abcdefg"` => `"ab ... fg"`). Create a similar function `row_limit` with the same behaviour (with string as param instead) to be used in `dense_cliffords.jl`. Parametrize each `show` function, so the the user can choose each `limit`/`limit_vertical`

## How?
```Julia
t = random_destabilizer(100)
#or
t = random_stabilizer(100)
#or
t = random_pauli(100) #[for Pauli, show function has only one extra parameter: limit (the row limit)]
#or
t = random_clifford(100)
show(stdout::IO, t, -1, -1)
#or
show(stdout::IO, t, 15, 7)
#or
print(t)
```
## Output example
```
X________________________ ... _______________________ ⟼  + YZ_Y__Z_ZXXZXZYZYXY_Z_XYZ ... ZYXYZZZ_YYY__XYZYX__ZYZ__Z
_X_______________________ ... _______________________ ⟼  + Z__YZ_XZ_Z_ZZXYZZYZ_YZZZX ... XZXZY_ZYXXX_XZYZXZ_YXXYX_Y
__X______________________ ... _______________________ ⟼  + _Y____Y_X_YZX_X_ZZ_XXY__Y ... _YZZZ__YXZY_Z_YYX__YZXY_Z_
___X_____________________ ... _______________________ ⟼  + XY_ZX_ZXYXZZ__ZZ_X__YZY_Z ... XX_ZXY_ZXYYYXYXYYYZZYYY_YX
____X____________________ ... _______________________ ⟼  + ZXZYZZY_ZYYXY_ZXYYZ_Z_XY_ ... ZZ____Z_XXZYZ__YYYZYZXY_XZ
_____X___________________ ... _______________________ ⟼  + XZZXZZ__XY_X____X__Y_Y_X_ ... XZZX_XZ_ZZYZX_XYZZ_XXXXY__
______X__________________ ... _______________________ ⟼  - YZXXXY_XZ_ZXZZ_YXY_XZXXXZ ... ZXZZ_ZZXX_Z__ZXXX__XXZ_YZX
_______X_________________ ... _______________________ ⟼  - ______Y_ZZZXZXY_YXYYY___Z ... XYZXZX_XXZ_ZXYZZZY_Z_YXZX_
________X________________ ... _______________________ ⟼  + ZX___Y_XZZY_XYZXXZ_XX_Z__ ... XZ__Y_ZYZZXYXX_XYXXZ_XZYYX
_________X_______________ ... _______________________ ⟼  - ZY_XX_XXYXXXXYZYXXYYYYZY_ ... ZYZ_Y__ZXYXZY___ZYXXZ_YZXZ
[ ..... ]
_________________________ ... ____________X__________ ⟼  + ZZXZ_X__YZ_YYZ_XX_Y_Y__X_ ... ZZZY__YX_YX_XY__XZYXXZ_YYZ
_________________________ ... _____________X_________ ⟼  + _Y_XXXXXYZ_ZY_YYZ_ZYXYZY_ ... XXX_Y_XZZYXYZY_XYYXZXY_YYY
_________________________ ... ______________X________ ⟼  + _YYXYYYXXYXZZY_ZYZYY_ZY__ ... _Y_XZ_XZZZXX__YX__YYYXZXXZ
_________________________ ... _______________X_______ ⟼  + ZYXXZY_XZX_XZ_ZYXYXZ_ZXXX ... XZZX_XYXYXXYXXXYYXY__XYZXZ
_________________________ ... ________________X______ ⟼  - Z_XXXY_ZZXZZYZZY_Z_XY__XY ... _ZX_YYZY_ZZY_YYXXY_YZ_X_Y_
_________________________ ... _________________X_____ ⟼  + XYXZ_XZ_ZZXXZ_YZZ__X_YYY_ ... ZX_X_____XXYYZZY__Z__ZXX__
_________________________ ... __________________X____ ⟼  - _ZX_XXXZZ_ZZXYXZ__XZ_Z_ZX ... _XZYX_XZYXZZZ_Z_XY_YXZZXZ_
_________________________ ... ___________________X___ ⟼  - YYXY_XZXY__YYZYYZY_XY_YXY ... YZYZXYYZXXYY_X_Z___Z_XZZYZ
_________________________ ... ____________________X__ ⟼  + _YZXZ_XY___YY_XXX_Z__ZZYX ... ____ZZXZ_ZYZ_X_ZXXYX_Z_YXZ
_________________________ ... _____________________X_ ⟼  - XZZZXYZ_YYZ_YYXZ_YZZXZYYZ ... Y___XZZYZYZ_ZX__Y_X_ZY___Y
_________________________ ... ______________________X ⟼  - _YZXZYZ_Y__X_ZZXXZZXYYX_X ... ZZZXXZYZYXX_XXZ_YYZZ__Z_Y_
Z________________________ ... _______________________ ⟼  + _ZZ_X_XXYXYY__XZ__XYYYX__ ... ZZZYX_YXXYZZZXXXYYYZX_XY_Z
_Z_______________________ ... _______________________ ⟼  + _YXYXYZXX_ZZZ_YZXZXZY__YY ... _ZZZ__XY_XYXXYYY__XZXZZYY_
__Z______________________ ... _______________________ ⟼  - _ZXY_XY_XYYXZ__YXY_XZZZXY ... X_Y_YZ_YZ__ZYYY_YZXY__XXZY
___Z_____________________ ... _______________________ ⟼  + ZYZYXYY_ZY_YZZ_Z__YZXZZYZ ... _ZY_YXXXYXXXY_XXXXYXZX__YY
____Z____________________ ... _______________________ ⟼  + XZZY__ZYZYYZYX_XXXYYZY_XZ ... X__XXY_XZ_Y_YXZXZZZ_X__XZ_
_____Z___________________ ... _______________________ ⟼  + ZXX_ZXZYY_Y_ZYYY_XZX_Y_YZ ... X___ZX__YYXXX_YX__XYZ___XZ
______Z__________________ ... _______________________ ⟼  - YXX_Y_YZ_YX_YYX_YXXY____Z ... _YZXX_ZZZY_Y_YZYY___YXZZZX
_______Z_________________ ... _______________________ ⟼  + X_YXY___YX_X_ZYYY__YZZY__ ... ZYXYYYZZX_ZZXZYXYX___XYY_Z
________Z________________ ... _______________________ ⟼  + ZX_X_ZZXZ_YXZ_Z_XZ_XX__XZ ... _Z___YZ_XZYXXYYY__ZXX_Z_ZY
_________Z_______________ ... _______________________ ⟼  - ZZYX____Y_XZ_X_Z_XYXZZ_XX ... YZ_ZYZ_X_Z_YXXY_YXYYZZZZXY
[ ..... ]
_________________________ ... ____________Z__________ ⟼  + X_YZ_YZZYYZYZX__Y_XZXZYXX ... _Z_XXYY_YYZZXXYXX_YXX__ZZZ
_________________________ ... _____________Z_________ ⟼  - YYY_ZZ_YZYZXXZYYYZ__ZXZYY ... ZZYZXZZZYXYZXX__YZXZZZ_ZZX
_________________________ ... ______________Z________ ⟼  + YX_XY_XZ____YZXZYX_YX_Z__ ... Y__XXZ__XYX_Z_XXZXXZZYZXX_
_________________________ ... _______________Z_______ ⟼  + XXXYX_Z_ZZXZYXZZ____YZXX_ ... YZ__Y__XZZ__ZYZYYZZY_YZZYY
_________________________ ... ________________Z______ ⟼  - XZYYYXXX_YXY__YXYXYXZ____ ... X_YX_ZZX_Y_X_X___XYYY_ZYYY
_________________________ ... _________________Z_____ ⟼  - ZXYYYXY__ZZXZXXYZ_ZXZYZZY ... _YZXXYYZXZYYX__ZXYYY_ZZ_ZY
_________________________ ... __________________Z____ ⟼  - XXXXXZXXXZ_ZXZXYYZ_XYZ_Y_ ... _ZX_ZZYXX_YXXZX_XYZX_ZY_XX
_________________________ ... ___________________Z___ ⟼  + __Z__Z_____XXYYZX__ZYZYZ_ ... Z_ZZZZZ_XZYYX_XYYYZXZZZXZ_
_________________________ ... ____________________Z__ ⟼  - XX_YY_XXZY_YXZZZY_X__YZYY ... Y_ZXZXY_X__YZZX__YZXX__YXX
_________________________ ... _____________________Z_ ⟼  - YXXZYYYZXX__XZY_ZX___Y_XZ ... XXX__XZ_Y__YXXX_ZXYYZZZZZZ
_________________________ ... ______________________Z ⟼  + X_ZXYYX_YZXZY_ZYYZX_YYXYX ... XXX_YZ__YZ_YZXYZZZXYYYYYYZ
```

And shorter:

```
X______ ... _____ ⟼  + YZ_Y__Z ... __ZYZ__Z
_X_____ ... _____ ⟼  + Z__YZ_X ... _YXXYX_Y
__X____ ... _____ ⟼  + _Y____Y ... _YZXY_Z_
[ ..... ]
_______ ... _X___ ⟼  - YYXY_XZ ... _Z_XZZYZ
_______ ... __X__ ⟼  + _YZXZ_X ... YX_Z_YXZ
_______ ... ___X_ ⟼  - XZZZXYZ ... X_ZY___Y
_______ ... ____X ⟼  - _YZXZYZ ... ZZ__Z_Y_
Z______ ... _____ ⟼  + _ZZ_X_X ... YZX_XY_Z
_Z_____ ... _____ ⟼  + _YXYXYZ ... XZXZZYY_
__Z____ ... _____ ⟼  - _ZXY_XY ... XY__XXZY
[ ..... ]
_______ ... _Z___ ⟼  + __Z__Z_ ... ZXZZZXZ_
_______ ... __Z__ ⟼  - XX_YY_X ... ZXX__YXX
_______ ... ___Z_ ⟼  - YXXZYYY ... YYZZZZZZ
_______ ... ____Z ⟼  + X_ZXYYX ... XYYYYYYZ
```

### CODE REVIEW

**Comment by Krastanov** [comment]
This looks great, thank you! I will provide a few comments on the API shortly, mostly having to deal with using `displaysize` instead of custom keyword arguments for `show`. It would probably be cleaner to keep `show` simple, without keyword arguments, and to make a new private `_show` that has the columnwidth argument. Then `show` can use `displaysize(io)` to decide the number of columns and call the private `_show`. The value of this approach is that we reuse most of Julia's machinery for these things, follow the approach established by the Base code for Array, and keep the public `show` simple. This would also make it easier to take into account `:compact` hints in the future.

**Comment by adrianariton** [comment]
Thank you for the advice! I hope the new commit solves the issue! If not, I would very much appreciate some more input from you. 

Now one can limit the size of the output as such:
```
show(IOContext(stdout::IO, :limit => true, :displaysize=>(25,13)), t)
```

Output example for destabiliser:
```
- __XY__XZXZYY ... _XY_YZ_YZYZZ_
+ YYYZ_Y_YX_X_ ... X_YZZY_YYXYZX
- YZZ_YYXYX_ZX ... _Z_XZZX___ZXZ
+ YZXYYZXZX__X ... YXYZZXXX_XZ_Y
- YZ__YZZ_XYXZ ... YZXZYYYYYXYZX
+ YZY_Y_XYXYYZ ... ZX_XYZZ_XY_YZ
[ ..... ]
- XZYYZZXYZY_X ... ZXZ_ZY_ZYYZYY
- YYXXYZXYYZYX ... ZZYZYYY_ZYX__
+ Y__Z_YZY_X_Y ... YZYYZXXXZ_Y__
+ Z_XYZXZZXZY_ ... Y_ZYYZZYX__Y_
- XX__YZYXZYZY ... X_ZXYXZZXX_Z_
- YXZ__ZZ__ZYZ ... Z_XXZ_Z_XZXZY
+ XZYYZZYZ_X__ ... YYYYZYY_YYXYY

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
- ZZXXZXY_XXXY ... ZX_Y_XYYZYZ_Y
- X_ZY_ZY_ZYZZ ... Z_YZYZ_X__YYX
+ _XYYXXYYXZ__ ... ZYYX_ZY___Y_Y
+ ZYZ_XZ_ZXYY_ ... ZZYXY_X_ZYY_Y
+ YYYZ_Y_ZYYXX ... XZ__ZX_YYYXYY
- XZZX_XXXYZXY ... __XZXXYZYZ_XZ
[ ..... ]
+ _XY_ZXZXZZ__ ... YYZXY_YZYZ_XY
+ YZZZYYX__ZXY ... ZZYZXYY_YY___
+ YZY_YZ_XZ_ZY ... Y_YYYX_ZYX_YZ
+ YZYXX_YXX_XY ... _ZY_ZXYZZZ_XX
- XYZXY_X_X_XX ... XYZ_ZZ_XZ_ZXX
- ZZZZY__ZYXZY ... XZZX__ZZXZZ_Y
- XZX_YY_XZZZY ... YXY_XZZYXX__X
```

Or use `show(IOContext(stdout::IO, :limit => false), t)` for full output!

**Comment by Krastanov** [comment]
This looks really great, thank you! Could you add yourself to the CONTRIBUTORS file and undo the changes to .gitignore? I think this is good to merge after that (will wait on tests and check for other things to polish).

**Comment by adrianariton** [comment]
Thank you! I added myself to the contributors file and fixed `gitignore`!

**Comment by Krastanov** [comment]
I made a few changes and pushed them in a new branch building on top of this one here https://github.com/Krastanov/QuantumClifford.jl/pull/98

**Pull request closed without merging**
